version: 1.0.{build}
before_build:
- md %APPVEYOR_BUILD_FOLDER%\build
- cd %APPVEYOR_BUILD_FOLDER%\build
- cmake -G "Visual Studio 12 Win64" -DOPTDBG=1 ..
- cd ..
build:
  project: build\rocksdb.sln
  parallel: true
  verbosity: minimal
test:
test_script:
- ps: build_tools\run_ci_db_test.ps1
notifications:
  - provider: Email
    to:
      - svmtrocksdb@microsoft.com
    subject: "Build {{status}}"
    message: "{{message}}, {{commitId}}, ..."
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
